seed: 0
run_status: 'train'
output_dir: './output'  # 当前不支持自定义修改，请勿修改该默认值
load_checkpoint: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
resume_training: False

# context
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: "--opt_level=0"
  max_call_depth: 10000
  save_graphs: False
  device_id: 0

# aicc
remote_save_url: "Please input obs url on AICC platform."

# runner
runner_config:
  epochs: 15
  batch_size: 64
  image_size: 224
  sink_mode: False
  sink_size: 2
runner_wrapper:
  type: FilipTrainOneStepWithLossScaleWrapper

# parallel
use_parallel: True
parallel:
  parallel_mode: 0 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: True
  enable_alltoall: False
  full_batch: False
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: False
  strategy_ckpt_save_file: "./ckpt_strategy.ckpt"
parallel_config:
  data_parallel: 8
  model_parallel: 1
  expert_parallel: 1
  pipeline_stage: 1
  optimizer_shard: False
  micro_batch_num: 1
  gradient_aggregation_group: 4
micro_batch_interleave_num: 1

# moe
moe_config:
  expert_num: 1
  capacity_factor: 1.05
  aux_loss_factor: 0.05
  num_experts_chosen: 1

# recompute
recompute_config:
  recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: False

# autotune
auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

# profile
profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True

# Trainer
trainer:
  type: itr
  model_name: 'filip'

# train dataset
train_dataset: &train_dataset
  data_loader:
    type: ImageToTextRetrievalDataset
    dataset_dir: ""
    shuffle: True
  transforms:
    - type: Decode
    - type: RandomResizedCrop
      size: 224
      scale: [0.2, 1.0]
      interpolation: bicubic
    - type: RandomHorizontalFlip
      prob: 0.5
    - type: RandomColorAdjust
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
    - type: ToTensor
    - type: Normalize
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]
      is_hwc: False
  project_columns: ["image", "token"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 64
  repeat: 1
  numa_enable: False
  prefetch_size: 1
  seed: 0
train_dataset_task:
  type: ImageToTextRetrievalDataset
  dataset_config: *train_dataset

# eval dataset
eval: &eval_dataset
  data_loader:
    type: ImageToTextRetrievalDataset
    dataset_dir: ""
    shuffle: True
  transforms:
    - type: Decode
    - type: RandomResizedCrop
      size: 224
      scale: [0.2, 1.0]
      interpolation: bicubic
    - type: RandomHorizontalFlip
      prob: 0.5
    - type: RandomColorAdjust
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
    - type: ToTensor
    - type: Normalize
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]
      is_hwc: False
  project_columns: ["image", "token"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 64
  repeat: 1
  numa_enable: False
  prefetch_size: 1
  seed: 0
eval_dataset_task:
  type: ImageToTextRetrievalDataset
  dataset_config: *eval_dataset

# model
model:
  arch:
    type: FilipModel
  model_config:
    type: FilipConfig
    text_config:
      type: FilipTextConfig
      hidden_size: 768
      vocab_size: 21128
      max_position_embeddins: 32
      num_hidden_layers: 12
    vision_config:
      type: FilipVisionConfig
      hidden_size: 1024
      image_size: 224
      patch_size: 14
      num_hidden_layers: 24
      token_learner: True
      num_tokens: 24
      num_token_groups: 8
      token_learner_dropout: 1.0
    dtype: float16
    checkpoint_name_or_path: ""
    projection_dim: 256
    ratio: 64
    batch_size: 64
    recompute: False

# lr sechdule
lr_schedule:
  type: CosineDecayLR
  max_lr: 0.00005
  min_lr: 0.
  decay_steps: 780
layer_scale: False
layer_decay: 0.65

# optimizer
optimizer:
  type: Lamb
  eps: 0.000001
  weight_decay: 0.0003
lr_scale: False
lr_scale_factor: 256
no_decay_params: ['positional_embedding', 'class_embedding', 'scale', 'bias', 'ln', 'bn']

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: SummaryMonitor
    keep_default_action: True
  - type: CheckpointMointor
    prefix: "mindformers"
    save_checkpoint_steps: 100
    integrated_save: True
    async_save: False
  - type: ObsMonitor
eval_callbacks:
  - type: ObsMonitor

# processor
processor:
  type: FilipProcessor
  feature_extractor:
    type: FilipFeatureExtractor
    image_feature_extractor:
      type: FilipImageFeatureExtrator
      image_resolution: 224
  tokenizer:
    type: FilipTokenizer
