# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
   configuration: docs/readthedocs/source_zh_cn/conf.py

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/readthedocs/requirements.txt
    - requirements: requirements.txt
    - method: setuptools
      path: .
